### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [Hyldem0er/Skirnir#57]
python main.py --ui                                                                                                                 [ 3:07PM 1 ⨯ ]

Traceback (most recent call last):
  File "/root/Desktop/OSINT/Skirnir/main.py", line 1, in <module>
    from src.ui import MainWindow
  File "/root/Desktop/OSINT/Skirnir/src/ui/MainWindow.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

can you help?

**Comment by Hyldem0er** [comment]
Hello,

The module `loguru` is not installed on your laptop. You should install it with other required libraries using `pip`. Below are the instructions to set up the environment and install the necessary libraries (you can go directly to step 3) :

1. **Create a Python environment (optional but strongly recommended)**

```bash
python3 -m venv env
```

2. **Activate the Python environment (optional but strongly recommended)**

- **Linux/MacOS:**

```bash
source env/bin/activate
```

- **Windows:**

```bash
.\env\Scripts\activate
```

3. **Install requirements**

```bash
pip install -r requirements.txt
```

4. **Launch the Skirnir program (User Interface)**

```bash
python3 main.py --ui
```

For more detailed information, please refer to the [Skirnir Installation Guide](https://hyldem0er.gitbook.io/skirnir/installation).

**Comment by shanow7** [comment]
python3 main.py --ui                                                                                                                     [ 5:08AM 1 ⨯ ]
Traceback (most recent call last):
  File "/root/Desktop/OSINT/Skirnir/main.py", line 1, in <module>
    from src.ui import MainWindow
  File "/root/Desktop/OSINT/Skirnir/src/ui/MainWindow.py", line 7, in <module>
    from src.ui.WorkerThread import WorkerThread
  File "/root/Desktop/OSINT/Skirnir/src/ui/WorkerThread.py", line 2, in <module>
    from src.utils.start_research import start_profile_research
  File "/root/Desktop/OSINT/Skirnir/src/utils/start_research.py", line 2, in <module>
    from src.surface_crawl.surface_crawl import surface_crawl
  File "/root/Desktop/OSINT/Skirnir/src/surface_crawl/surface_crawl.py", line 4, in <module>
    from src.surface_crawl.Browser import Browser
  File "/root/Desktop/OSINT/Skirnir/src/surface_crawl/Browser.py", line 1, in <module>
    from src.surface_crawl.create_url_or_query import *
  File "/root/Desktop/OSINT/Skirnir/src/surface_crawl/create_url_or_query.py", line 1, in <module>
    from duckduckgo_search import DDGS
ModuleNotFoundError: No module named 'duckduckgo_search'

:(

**Comment by Hyldem0er** [comment]
Can you try to execute the program this way : `.\env\Scripts\python.exe main.py --ui` if you use a env

**Comment by shanow7** [comment]
python3 .\env\Scripts\python.exe main.py --ui                                                                                           
python3: can't open file '/root/Desktop/OSINT/Skirnir/.envScriptspython.exe': [Errno 2] No such file or directory

**Comment by Hyldem0er** [comment]
Please remove “python 3” before “.\NScripts\Npython.exe main.py --ui”.
“.\NScripts\Npython.exe” replaces the ‘python3’ command.
